const usernameList = [
  'achedegree',
  'republicanunion',
  'announcercaterer',
  'extrapopular',
  'involvejagged',
  'rubkerching',
  'efficiencymarmalade',
  'nounchimney',
  'cadgeexultant',
  'oafishshut',
  'cartilagepleat',
  'pepperycheater',
  'molarcandidate',
  'mazipangodly',
  'paperclipstailor',
  'chewicky',
  'radianttapioca',
  'yearlydogwatch',
  'dingalingsnobby',
  'coralnovel',
  'ascensionkingfu',
  'mizzenmastgrove',
  'clearingnightshirt',
  'associatecurry',
  'militaryeventually',
  'limbichomeplate',
  'sablecuff',
  'meatjackass',
  'thornsincomplete',
  'bightrearend',
  'datebewildered',
  'enchantburnish',
  'adamantvowel',
  'affectedboomerang',
  'spotlessfinish',
  'generosityoik',
  'bedrockcarol',
  'skatingbitter',
  'savorclash',
  'smithinghearts',
  'lowquarterly',
  'spreadjibe',
  'humoroussoft',
  'guillemotintrusion',
  'lonegradually',
  'yelpheath',
  'amusingwordy',
  'imaginaryenthralled',
  'hermitlearning',
  'babytreenail',
  'throbafternoon',
  'colouredjigsaw',
  'fortressunlined',
  'nunfascinated',
  'beingnice',
  'multiplefootball',
  'southeastnumber',
  'lardprofession',
  'exchangeoffense',
  'authoritylice',
  'observantgate',
  'deliciouseyebrow',
  'assaultdeck',
  'fieldamount',
  'unlessdetail',
  'celerytea',
  'tritebathe',
  'dodgerdiver',
  'constantlylabor',
  'enthralledlisten',
  'wideeyedclutter',
  'cabbagegrowling',
  'cognitiveimprobable',
  'nautiluslong',
  'sleddingtrenchcoat',
  'harrowquality',
  'gherkinsfries',
  'neighbogus',
  'fanaticalfighting',
  'purpledog',
  'hotdogender',
  'couplecross',
  'spaghettibalanced',
  'reflectiveaffinity',
  'octopusstrongly',
  'admissionculottes',
  'angerhick',
  'elevatorovercome',
  'graduatetrout',
  'lamentablescreech',
  'ridiculouscabinet',
  'clankliberated',
  'doesavaricious',
  'coarsecurrently',
  'dependablerare',
  'lettuceeducator',
  'clothenest',
  'outfitdecipher',
  'ultrasymptom',
  'sodvicar',
  'personnelguineafowl',
  'preachalluring',
  'cyclemath',
  'woundgive',
  'washhandmade',
  'caftanbeautiful',
  'thoseamazon',
  'strakehumble',
  'vinefanny',
  'vacationround',
  'chordcommon',
  'fancygross',
  'fateattractive',
  'proclaimabout',
  'conduitgerman',
  'sunrisehum',
  'heapgam',
  'floorbudget',
  'boldinsect',
  'hatefullacrosse',
  'apologizevalue',
  'extensionvisa',
  'rowinglike',
  'absorbedextent',
  'tunicpitch',
  'recipetransition',
  'anythingreligious',
  'portfoliorestore',
  'musselsnatch',
  'pluralelytra',
  'examinescientific',
  'joystickshift',
  'applauddinner',
  'sdraughtstudious',
  'factcobblestone',
  'javelinraspberry',
  'attendlemon',
  'upstairsstreamer',
  'cattlejudgment',
  'newspaperslender',
  'seriouslygiven',
  'volkswagonpopped',
  'unhealthychemist',
  'onerousastronomer',
  'yakimpish',
  'authorrecovery',
  'cyclonicnegotiate',
  'junkieforce',
  'prettyingmale'
]

const emailUsernames = [
  'tablecrying',
  'undyingpearl',
  'poweredsugar',
  'waterzombie',
  'wardguardian',
  'melonshears',
  'bottlehoglin',
  'emeraldenderman',
  'creamwheat',
  'slimeballcauldron',
  'loyaltylog',
  'netherblazerod',
  'netheriteshipwreck',
  'spawninfested',
  'fireworkjack',
  'weightedmansion',
  'riptidesilk',
  'barreldried',
  'crystalsoutpost',
  'swampplanks',
  'soupdrowned',
  'quartzpainting',
  'nuggetcarrot',
  'jigsawobsidian',
  'sacfan',
  'fungusbucket',
  'nautilusmellohi',
  'graniteglass',
  'boatmodified',
  'bottlenetherrack',
  'frostedjigsaw',
  'cavetundra',
  'smallriver',
  'blackstonefern',
  'compassbarrens',
  'stradaffinity',
  'doorpigman',
  'crossbowweeping',
  'endcitymycelium',
  'seagrasspeony',
  'myceliumpoppy',
  'junglemilk',
  'structuremansion',
  'membraneelytra',
  'shroomlightslime',
  'hoetipped',
  'phantomdirt',
  'sharpnessexperience',
  'midlandslilypad',
  'cactuspiglin'
]

const emailTypes = [
  'gmail.com',
  'aol.com',
  'msn.com',
  'hotmail.com',
  'bellsouth.net',
  'outlook.com',
  'yahoo.com',
  'unmarkedvan.gov'
]

const hereBeThoughts = [
  'This is a thought',
  'This is also a thought',
  'This is not a very well though out thought',
  'All womens are queens.',
  "If she breathes... she's a THOOOOOOT",
  "I'm just here so I won't get fined.",
  'I am so bad at coding',
  'This bootcamp is destroying me',
  "I'm never going to be good enough",
  'End my suffering',
  'Imma go commit die now',
  'How does this work?',
  'All your base are belong to us'
]

const hereBeReactions = [
  'omg, no way',
  'liked this thought',
  'disliked this thought',
  "stop thoughting, it doesnt suit you",
  'yooo this is wack',
  'im a pirate',
  'no one asked',
  "i showed my dog this clip and now he's a wolf",
  'does anyone ever wonder how we got here, like REALLY got here?',
  "i'd agree, but you're wrong, so I disagree",
  'Go Pack Go',
  'O-H... I-O!',
  'I too was repulsed by the weakness of my flesh'
]

const getRandomUsername = () => `${usernameList[Math.floor(Math.random() * usernameList.length)]}`
const getRandomEmail = () => `${emailUsernames[Math.floor(Math.random() * emailUsernames.length)]}@${emailTypes[Math.floor(Math.random() * emailTypes.length)]}`
const getRandomThought = () => `${hereBeThoughts[Math.floor(Math.random() * hereBeThoughts.length)]}`
const getRandomReaction = () => `${hereBeReactions[Math.floor(Math.random() * hereBeReactions.length)]}`

module.exports = {
  getRandomUsername,
  getRandomEmail,
  getRandomThought,
  getRandomReaction
}